// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rdxtbdovcppvmieiapxr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkeHRiZG92Y3Bwdm1pZWlhcHhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg3MjU0MzAsImV4cCI6MjA1NDMwMTQzMH0.n514jVlFaZpIuInliTDnaPEA9npIEdeCksQYBX3Bj1Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);